spring:
  application:
    name: cruncher
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:postgresql://192.168.2.7:5432/parqueadero
    username: root
    password: wilmar
  jpa:
    hibernate:
      ddl-auto: none

server:
  address: 192.168.2.7
  port: 9000