spring:
  application:
    name: cruncher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.200.46:5432/HORUS
    username: postgres
    password: CETAd2016
  jpa:
    hibernate:
      ddl-auto: none

server:
  address: 192.168.250.119
  port: 9000